# Generated by Django 3.2.12 on 2022-02-04 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='название')),
                ('description_short', models.CharField(max_length=500, verbose_name='краткое описание')),
                ('description_long', models.TextField(verbose_name='полное описание')),
                ('latitude', models.FloatField(verbose_name='lat')),
                ('lontitude', models.FloatField(verbose_name='lng')),
            ],
        ),
    ]
