# Generated by Django 3.2.12 on 2022-02-04 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='order_number',
        ),
        migrations.AddField(
            model_name='image',
            name='position',
            field=models.IntegerField(default=1, verbose_name='позиция'),
            preserve_default=False,
        ),
    ]
