# Generated by Django 3.2.12 on 2022-02-08 13:08

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_alter_image_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='lontitude',
            new_name='longitude',
        ),
        migrations.AlterField(
            model_name='place',
            name='description_long',
            field=tinymce.models.HTMLField(verbose_name='полное описание'),
        ),
        migrations.AlterUniqueTogether(
            name='place',
            unique_together={('longitude', 'latitude')},
        ),
    ]
