# Generated by Django 3.2.12 on 2022-02-15 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_auto_20220215_1242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='title',
            new_name='place',
        ),
    ]
